/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.OrderController;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.CartItem;
import model.User;
import util.AppSession;
import util.CartHelper;
import util.Format;
import util.Style;
import util.Theme;

/**
 *
 * @author Lenovo
 */
public class CheckoutPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckoutPanel
     */
    private ShopFrm shell;
    private final OrderController controller = new OrderController();
    private DefaultTableModel summaryModel;

    public CheckoutPanel(ShopFrm shell) {
        this.shell = shell;
        initComponents();

        summaryModel = new DefaultTableModel(new Object[]{"Món", "SL", "Thành tiền"}, 0) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        tblSummary.setModel(summaryModel);
        tblSummary.getColumnModel().getColumn(0).setPreferredWidth(220);
        tblSummary.getColumnModel().getColumn(1).setPreferredWidth(40);

        ButtonGroup group = new ButtonGroup();
        group.add(rdoCod);
        group.add(rdoVnpay);
        rdoCod.setSelected(true);
        rdoVnpay.setEnabled(false);

        applyStyle();
        btnBack.addActionListener(e -> shell.showCart());
        btnPlace.addActionListener(e -> placeOrder());
    }

    private void applyStyle() {
        remove(pnlMain);
        javax.swing.JPanel center = new javax.swing.JPanel(new java.awt.BorderLayout());
        center.setBorder(Theme.pad(12, 16));
        center.add(pnlMain, java.awt.BorderLayout.NORTH);
        add(center, java.awt.BorderLayout.CENTER);
        ((java.awt.GridLayout) pnlMain.getLayout()).setHgap(16);
        java.awt.GridLayout gl = (java.awt.GridLayout) pnlForm.getLayout();
        gl.setVgap(10);
        gl.setHgap(12);
        pnlFormWrap.add(pnlForm, java.awt.BorderLayout.CENTER);   // thẻ trái cao bằng thẻ phải
        tblSummary.setPreferredScrollableViewportSize(new java.awt.Dimension(300, 230));

        setBackground(Theme.BG);
        Style.page(pnlTop, pnlMain, pnlFormWrap, center);
        Style.transparent(pnlMethod, pnlPay);
        Style.card(pnlForm, "Thông tin giao hàng");
        Style.card(scrollSummary, "Đơn hàng của bạn");
        Style.bar(pnlBottom);

        Style.heading(lblTitle);
        for (javax.swing.JLabel l : new javax.swing.JLabel[]{jLabel1, jLabel2, jLabel3, jLabel4, jLabel5}) {
            Style.label(l);
        }
        for (javax.swing.JTextField f : new javax.swing.JTextField[]{txtName, txtPhone, txtAddress, txtNote}) {
            Style.field(f);
        }
        Style.radio(rdoCod);
        Style.radio(rdoVnpay);
        Style.money(lblTotal);
        Style.primary(btnPlace);
        Style.secondary(btnBack);
        Style.table(tblSummary, 1, 2);
    }

    public void reload() {
        summaryModel.setRowCount(0);
        for (CartItem it : CartHelper.getItems()) {
            summaryModel.addRow(new Object[]{
                it.getName(), it.getQuantity(), Format.money(it.getSubtotal())
            });
        }
        lblTotal.setText("Tổng: " + Format.money(CartHelper.total()));
        btnPlace.setEnabled(!CartHelper.getItems().isEmpty());

        User u = AppSession.getCurrentUser();
        if (txtName.getText().trim().isEmpty() && u != null && u.getFullName() != null) {
            txtName.setText(u.getFullName());
        }
    }

    private void placeOrder() {
        String method = rdoVnpay.isSelected() ? "VNPay" : "COD";
        try {
            int id = controller.placeOrder(txtName.getText(), txtPhone.getText(),
                    txtAddress.getText(), txtNote.getText(), method,
                    new ArrayList<>(CartHelper.getItems()));
            CartHelper.clear();
            txtNote.setText("");
            JOptionPane.showMessageDialog(this,
                    "Đặt hàng thành công! Mã đơn của bạn: #" + id
                    + "\nBạn thanh toán khi nhận hàng (COD).");
            shell.showOrders();
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Không thể đặt hàng", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlFormWrap = new javax.swing.JPanel();
        pnlForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pnlMethod = new javax.swing.JPanel();
        rdoCod = new javax.swing.JRadioButton();
        rdoVnpay = new javax.swing.JRadioButton();
        scrollSummary = new javax.swing.JScrollPane();
        tblSummary = new javax.swing.JTable();
        pnlBottom = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        pnlPay = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        btnPlace = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setText("Đặt hàng");
        pnlTop.add(lblTitle);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlMain.setLayout(new java.awt.GridLayout(1, 2, 12, 12));

        pnlFormWrap.setLayout(new java.awt.BorderLayout());

        pnlForm.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin giao hàng"));
        pnlForm.setLayout(new java.awt.GridLayout(5, 2, 8, 8));

        jLabel1.setText("Người nhận");
        pnlForm.add(jLabel1);
        pnlForm.add(txtName);

        jLabel2.setText("Số điện thoại");
        pnlForm.add(jLabel2);
        pnlForm.add(txtPhone);

        jLabel3.setText("Địa chỉ giao hàng");
        pnlForm.add(jLabel3);
        pnlForm.add(txtAddress);

        jLabel4.setText("Ghi chú");
        pnlForm.add(jLabel4);
        pnlForm.add(txtNote);

        jLabel5.setText("Thanh toán");
        pnlForm.add(jLabel5);

        pnlMethod.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        rdoCod.setText("Tiền mặt (COD)");
        pnlMethod.add(rdoCod);

        rdoVnpay.setText("VNPay (sắp có)");
        pnlMethod.add(rdoVnpay);

        pnlForm.add(pnlMethod);

        pnlFormWrap.add(pnlForm, java.awt.BorderLayout.NORTH);

        pnlMain.add(pnlFormWrap);

        scrollSummary.setBorder(javax.swing.BorderFactory.createTitledBorder("Đơn hàng của bạn"));

        tblSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollSummary.setViewportView(tblSummary);

        pnlMain.add(scrollSummary);

        add(pnlMain, java.awt.BorderLayout.CENTER);

        pnlBottom.setLayout(new java.awt.BorderLayout());

        btnBack.setText("← Quay lại giỏ hàng");
        pnlBottom.add(btnBack, java.awt.BorderLayout.WEST);

        pnlPay.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setText("Tổng: 0 ₫");
        pnlPay.add(lblTotal);

        btnPlace.setText("Đặt hàng");
        pnlPay.add(btnPlace);

        pnlBottom.add(pnlPay, java.awt.BorderLayout.EAST);

        add(pnlBottom, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPlace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlFormWrap;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMethod;
    private javax.swing.JPanel pnlPay;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JRadioButton rdoCod;
    private javax.swing.JRadioButton rdoVnpay;
    private javax.swing.JScrollPane scrollSummary;
    private javax.swing.JTable tblSummary;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
