/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.AdminController;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import util.Format;
import util.Style;
import util.Theme;
/**
 *
 * @author Lenovo
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    private final AdminController controller = new AdminController();
    private final JLabel valRevenue = new JLabel("0");
    private final JLabel valOrders = new JLabel("0");
    private final JLabel valPending = new JLabel("0");
    private final JLabel valProducts = new JLabel("0");
    private DefaultTableModel topModel;
    private DefaultTableModel dayModel;

    public DashboardPanel() {
        initComponents();

        // 4 thẻ số liệu dựng bằng code, bỏ vào pnlCards (đã thiết kế GridLayout 1x4)
        pnlCards.add(Style.statCard("Doanh thu (đơn hoàn thành)", valRevenue, Theme.PRIMARY));
        pnlCards.add(Style.statCard("Tổng số đơn", valOrders, new java.awt.Color(0x1C7ED6)));
        pnlCards.add(Style.statCard("Đơn chờ xác nhận", valPending, new java.awt.Color(0xF59F00)));
        pnlCards.add(Style.statCard("Món đang bán", valProducts, new java.awt.Color(0x2B8A3E)));

        topModel = new DefaultTableModel(new Object[]{"Món bán chạy", "Đã bán", "Doanh thu"}, 0) {
            @Override
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblTop.setModel(topModel);
        dayModel = new DefaultTableModel(new Object[]{"Ngày", "Số đơn", "Doanh thu"}, 0) {
            @Override
            public boolean isCellEditable(int r, int c) { return false; }
        };
        tblDays.setModel(dayModel);

        applyStyle();
        btnRefresh.addActionListener(e -> reload());
    }

    private void applyStyle() {
        setBackground(Theme.BG);
        Style.page(pnlTop, pnlBody, pnlCards, pnlLists);
        pnlBody.setBorder(Theme.pad(4, 16));
        Style.heading(lblTitle);
        Style.secondary(btnRefresh);
        ((java.awt.GridLayout) pnlCards.getLayout()).setHgap(14);
        pnlCards.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 14, 0));
        ((java.awt.GridLayout) pnlLists.getLayout()).setHgap(14);
        Style.card(scrollTop, "Top 5 món bán chạy");
        Style.card(scrollDays, "7 ngày gần nhất");
        Style.table(tblTop, 1, 2);
        Style.table(tblDays, 1, 2);
        tblTop.getColumnModel().getColumn(0).setPreferredWidth(220);
        pnlTop.setBorder(Theme.pad(8, 16));
    }

    public void reload() {
        valRevenue.setText(Format.money(controller.revenue()));
        valOrders.setText(String.valueOf(controller.totalOrders()));
        valPending.setText(String.valueOf(controller.pendingOrders()));
        valProducts.setText(String.valueOf(controller.activeProducts()));

        topModel.setRowCount(0);
        for (Object[] r : controller.topProducts(5)) {
            topModel.addRow(new Object[]{r[0], r[1], Format.money((double) r[2])});
        }
        dayModel.setRowCount(0);
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        for (Object[] r : controller.lastDays(7)) {
            dayModel.addRow(new Object[]{f.format((java.util.Date) r[0]), r[1], Format.money((double) r[2])});
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        pnlBody = new javax.swing.JPanel();
        pnlCards = new javax.swing.JPanel();
        pnlLists = new javax.swing.JPanel();
        scrollTop = new javax.swing.JScrollPane();
        tblTop = new javax.swing.JTable();
        scrollDays = new javax.swing.JScrollPane();
        tblDays = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnlTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setText("Tổng quan");
        pnlTop.add(lblTitle);

        btnRefresh.setText("Làm mới");
        pnlTop.add(btnRefresh);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlBody.setLayout(new java.awt.BorderLayout());

        pnlCards.setLayout(new java.awt.GridLayout(1, 4));
        pnlBody.add(pnlCards, java.awt.BorderLayout.NORTH);

        pnlLists.setLayout(new java.awt.GridLayout(1, 2));

        tblTop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTop.setViewportView(tblTop);

        pnlLists.add(scrollTop);

        tblDays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollDays.setViewportView(tblDays);

        pnlLists.add(scrollDays);

        pnlBody.add(pnlLists, java.awt.BorderLayout.CENTER);

        add(pnlBody, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlLists;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JScrollPane scrollDays;
    private javax.swing.JScrollPane scrollTop;
    private javax.swing.JTable tblDays;
    private javax.swing.JTable tblTop;
    // End of variables declaration//GEN-END:variables
}
