/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.HomeController;
import java.awt.BorderLayout;
import java.awt.Cursor;
import javax.swing.*;
import model.Category;
import util.Theme;
/**
 *
 * @author Lenovo
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    private final ShopFrm shell;
    private final HomeController controller = new HomeController();
    private final ProductGridPanel featuredGrid = new ProductGridPanel(4);
    public HomePanel(ShopFrm shell) {
        this.shell = shell;
        initComponents();

        JPanel wrap = new JPanel(new BorderLayout());
        wrap.setOpaque(false);
        wrap.setBorder(BorderFactory.createEmptyBorder(8, 6, 16, 6));
        wrap.add(featuredGrid, BorderLayout.NORTH);
        scrollFeatured.setViewportView(wrap);
        scrollFeatured.getViewport().setBackground(Theme.BG);
        scrollFeatured.getVerticalScrollBar().setUnitIncrement(16);

        btnViewMenu.addActionListener(e -> shell.showProducts(0, ""));
    }
    // Nạp lại dữ liệu mỗi lần vào trang chủ (ShopFrm gọi hàm này)
    public void reload() {
        pnlCategories.removeAll();
        for (Category c : controller.categories()) {
            JButton b = new JButton(c.getName());
            b.setFocusPainted(false);
            b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            b.addActionListener(e -> shell.showProducts(c.getId(), ""));
            pnlCategories.add(b);
        }
        pnlCategories.revalidate();
        pnlCategories.repaint();
        featuredGrid.setProducts(controller.index(), shell::showProductDetail);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHero = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlHeroBtn = new javax.swing.JPanel();
        btnViewMenu = new javax.swing.JButton();
        pnlBody = new javax.swing.JPanel();
        pnlCategories = new javax.swing.JPanel();
        scrollFeatured = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(250, 247, 242));
        setLayout(new java.awt.BorderLayout());

        pnlHero.setBackground(new java.awt.Color(232, 89, 12));
        pnlHero.setPreferredSize(new java.awt.Dimension(100, 170));
        pnlHero.setLayout(new java.awt.GridLayout(3, 1, 0, 6));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đói rồi? FastFood lo!");
        pnlHero.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Đồ ăn nóng hổi, giao nhanh tận nơi");
        pnlHero.add(jLabel2);

        pnlHeroBtn.setOpaque(false);

        btnViewMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewMenu.setForeground(new java.awt.Color(232, 89, 12));
        btnViewMenu.setText("Xem thực đơn");
        pnlHeroBtn.add(btnViewMenu);

        pnlHero.add(pnlHeroBtn);

        add(pnlHero, java.awt.BorderLayout.NORTH);

        pnlBody.setLayout(new java.awt.BorderLayout());

        pnlCategories.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh mục", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        pnlCategories.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pnlBody.add(pnlCategories, java.awt.BorderLayout.NORTH);

        scrollFeatured.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản phẩm nổi bật", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        pnlBody.add(scrollFeatured, java.awt.BorderLayout.CENTER);

        add(pnlBody, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlCategories;
    private javax.swing.JPanel pnlHero;
    private javax.swing.JPanel pnlHeroBtn;
    private javax.swing.JScrollPane scrollFeatured;
    // End of variables declaration//GEN-END:variables
}
