/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ProductController;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.*;
import model.Category;
import model.Product;
import util.Theme;
/**
 *
 * @author Lenovo
 */
public class ProductListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductListPanel
     */
    private final ShopFrm shell;
    private final ProductController controller = new ProductController();
    private final ProductGridPanel grid = new ProductGridPanel(4);
    private boolean loading = false;
    public ProductListPanel(ShopFrm shell) {
        this.shell = shell;
        initComponents();

        // Đặt lưới sản phẩm vào JScrollPane đã kéo thả
        JPanel wrap = new JPanel(new BorderLayout());
        wrap.setOpaque(false);
        wrap.setBorder(BorderFactory.createEmptyBorder(8, 6, 16, 6));
        wrap.add(grid, BorderLayout.NORTH);
        scrollProducts.setViewportView(wrap);
        scrollProducts.setBorder(null);
        scrollProducts.getViewport().setBackground(Theme.BG);
        scrollProducts.getVerticalScrollBar().setUnitIncrement(16);

        btnSearch.addActionListener(e -> search());
        txtSearch.addActionListener(e -> search());                     // Enter
        ddlCategory.addActionListener(e -> { if (!loading) search(); });
    }
    
    public void showWith(int categoryId, String keyword) {
        loading = true;
        ddlCategory.removeAllItems();
        ddlCategory.addItem(new Category(0, "Tất cả danh mục", ""));
        for (Category c : controller.categories()) {
            ddlCategory.addItem(c);
            if (c.getId() == categoryId) ddlCategory.setSelectedItem(c);
        }
        if (categoryId <= 0) ddlCategory.setSelectedIndex(0);
        loading = false;

        txtSearch.setText(keyword == null ? "" : keyword);
        search();
    }

    private void search() {
        Category c = (Category) ddlCategory.getSelectedItem();
        int catId = c == null ? 0 : c.getId();
        List<Product> list = controller.index(catId, txtSearch.getText().trim());
        lblCount.setText(list.size() + " món");
        grid.setProducts(list, shell::showProductDetail);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFilter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ddlCategory = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        lblCount = new javax.swing.JLabel();
        scrollProducts = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(250, 247, 242));
        setLayout(new java.awt.BorderLayout());

        pnlFilter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 12, 5));

        jLabel1.setText("Tên món:");
        pnlFilter.add(jLabel1);

        txtSearch.setColumns(20);
        txtSearch.setPreferredSize(new java.awt.Dimension(240, 28));
        pnlFilter.add(txtSearch);

        jLabel2.setText("Danh mục:");
        pnlFilter.add(jLabel2);

        ddlCategory.setPreferredSize(new java.awt.Dimension(200, 28));
        pnlFilter.add(ddlCategory);

        btnSearch.setText("Tìm kiếm");
        pnlFilter.add(btnSearch);
        pnlFilter.add(lblCount);

        add(pnlFilter, java.awt.BorderLayout.NORTH);
        add(scrollProducts, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<model.Category> ddlCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCount;
    private javax.swing.JPanel pnlFilter;
    private javax.swing.JScrollPane scrollProducts;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
