/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ProductController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.*;
import model.Product;
import util.Format;
import util.ImageUtil;
import util.Theme;
/**
 *
 * @author Lenovo
 */
public class ProductDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductDetailPanel
     */
    private final ShopFrm shell;
    private final ProductController controller = new ProductController();
    private final ProductGridPanel relatedGrid = new ProductGridPanel(4);
    private Product current;
    
    public ProductDetailPanel(ShopFrm shell) {
        this.shell = shell;
        initComponents();

        // Ô mô tả: chỉ đọc, tự xuống dòng, nền trong suốt
        txtDesc.setEditable(false);
        txtDesc.setLineWrap(true);
        txtDesc.setWrapStyleWord(true);
        txtDesc.setOpaque(false);
        scrollDesc.setBorder(null);
        scrollDesc.setOpaque(false);
        scrollDesc.getViewport().setOpaque(false);

        // Lưới sản phẩm liên quan
        JPanel wrap = new JPanel(new BorderLayout());
        wrap.setOpaque(false);
        wrap.add(relatedGrid, BorderLayout.NORTH);
        scrollRelated.setViewportView(wrap);
        scrollRelated.setBorder(null);
        scrollRelated.getViewport().setBackground(Theme.BG);

        // Sự kiện
        btnBack.addActionListener(e -> shell.goBack());
        btnAdd.addActionListener(e -> addToCart());
    }
    // ShopFrm gọi hàm này khi bấm vào một sản phẩm
    public void load(int productId) {
        Product p = controller.details(productId);
        if (p == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm.");
            return;
        }
        display(p, controller.related(p, 4));
    }

    // Đổ dữ liệu lên giao diện
    public void display(Product p, List<Product> related) {
        current = p;
        lblName.setText(p.getName());
        lblCategory.setText(p.getCategoryName() == null ? "" : "Danh mục: " + p.getCategoryName());
        lblPrice.setText(Format.money(p.getPrice()));
        txtDesc.setText(p.getDescription() == null ? "" : p.getDescription());
        txtDesc.setCaretPosition(0);

        boolean inStock = p.isAvailable() && p.getStock() > 0;
        lblStock.setText(inStock ? "Còn hàng (" + p.getStock() + ")" : "Hết hàng");
        lblStock.setForeground(inStock ? new Color(0x2B8A3E) : Theme.DANGER);
        spnQty.setModel(new SpinnerNumberModel(1, 1, Math.max(1, p.getStock()), 1));
        spnQty.setEnabled(inStock);
        btnAdd.setEnabled(inStock);

        lblImage.setIcon(null);
        lblImage.setText("Không có ảnh");
        ImageUtil.load(p.getImageUrl(), 380, 300, icon -> {
            if (icon != null) { lblImage.setText(null); lblImage.setIcon(icon); }
        });
        relatedGrid.setProducts(related, shell::showProductDetail);
    }

        private void addToCart() {
        if (current == null) return;
        String err = new controller.CartController().add(current, (int) spnQty.getValue());
        if (err != null) {
            JOptionPane.showMessageDialog(this, err);
            return;
        }
        int choice = JOptionPane.showOptionDialog(this,
                "Đã thêm " + current.getName() + " vào giỏ hàng.",
                "Giỏ hàng", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                null, new String[]{"Xem giỏ hàng", "Tiếp tục mua"}, "Tiếp tục mua");
        if (choice == 0) shell.showCart();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        pnlInfoTop = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        scrollDesc = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        pnlBuy = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        spnQty = new javax.swing.JSpinner();
        btnAdd = new javax.swing.JButton();
        pnlRelated = new javax.swing.JPanel();
        lblRelated = new javax.swing.JLabel();
        scrollRelated = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(250, 247, 242));
        setLayout(new java.awt.BorderLayout());

        pnlTop.setOpaque(false);
        pnlTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnBack.setText("← Quay lại");
        pnlTop.add(btnBack);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlMain.setOpaque(false);
        pnlMain.setLayout(new java.awt.BorderLayout());

        lblImage.setBackground(new java.awt.Color(243, 239, 232));
        lblImage.setForeground(new java.awt.Color(119, 119, 119));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setOpaque(true);
        lblImage.setPreferredSize(new java.awt.Dimension(380, 300));
        pnlMain.add(lblImage, java.awt.BorderLayout.WEST);

        pnlInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 24, 0, 0));
        pnlInfo.setOpaque(false);
        pnlInfo.setLayout(new java.awt.BorderLayout());

        pnlInfoTop.setOpaque(false);
        pnlInfoTop.setLayout(new java.awt.GridLayout(4, 1, 0, 4));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblName.setText("Tên sản phẩm");
        pnlInfoTop.add(lblName);

        lblCategory.setForeground(new java.awt.Color(119, 119, 119));
        lblCategory.setText("Danh mục");
        pnlInfoTop.add(lblCategory);

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(232, 89, 12));
        lblPrice.setText("0 ₫");
        pnlInfoTop.add(lblPrice);

        lblStock.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblStock.setText("Còn hàng");
        pnlInfoTop.add(lblStock);

        pnlInfo.add(pnlInfoTop, java.awt.BorderLayout.NORTH);

        scrollDesc.setPreferredSize(null);

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        scrollDesc.setViewportView(txtDesc);

        pnlInfo.add(scrollDesc, java.awt.BorderLayout.CENTER);

        pnlBuy.setOpaque(false);
        pnlBuy.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel5.setText("Số lượng:");
        pnlBuy.add(jLabel5);

        spnQty.setPreferredSize(new java.awt.Dimension(70, 32));
        pnlBuy.add(spnQty);

        btnAdd.setBackground(new java.awt.Color(232, 89, 12));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Thêm vào giỏ");
        btnAdd.setPreferredSize(new java.awt.Dimension(160, 36));
        pnlBuy.add(btnAdd);

        pnlInfo.add(pnlBuy, java.awt.BorderLayout.SOUTH);

        pnlMain.add(pnlInfo, java.awt.BorderLayout.CENTER);

        add(pnlMain, java.awt.BorderLayout.CENTER);

        pnlRelated.setOpaque(false);
        pnlRelated.setPreferredSize(new java.awt.Dimension(100, 400));
        pnlRelated.setLayout(new java.awt.BorderLayout());

        lblRelated.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblRelated.setText("Sản phẩm liên quan");
        pnlRelated.add(lblRelated, java.awt.BorderLayout.NORTH);
        pnlRelated.add(scrollRelated, java.awt.BorderLayout.CENTER);

        add(pnlRelated, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRelated;
    private javax.swing.JLabel lblStock;
    private javax.swing.JPanel pnlBuy;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlInfoTop;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlRelated;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JScrollPane scrollDesc;
    private javax.swing.JScrollPane scrollRelated;
    private javax.swing.JSpinner spnQty;
    private javax.swing.JTextArea txtDesc;
    // End of variables declaration//GEN-END:variables
}
